[package]
name = "genshin_gacha"
version = "0.2.0"
edition = "2021"
authors = ["lgou2w"]
description = "Manage and analyze your Genshin Impact gacha logs"
homepage = "https://github.com/lgou2w/genshin-gacha#readme"
repository = "https://github.com/lgou2w/genshin-gacha"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
anyhow = "1.0.69"
byteorder = "1.4.3"
chrono = { version = "0.4.24", default-features = false, features = ["std", "clock"] }
env_logger = "0.10.0"
form_urlencoded = "1.1.0"
futures-core = { version = "0.3.27", default-features = false }
lazy_static = "1.4.0"
log = "0.4.17"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite"] }
tauri = { version = "1", features = ["clipboard-all", "dialog-all", "path-all", "shell-all"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
tokio = { version = "1.25.0", features = ["full"] }
url = "2.3.1"
xlsxwriter = "0.5.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
