[package]
name = "hoyo_gacha"
version = "0.4.2"
edition = "2021"
authors = ["lgou2w"]
description = "An unofficial tool for managing and analyzing your miHoYo gacha records"
homepage = "https://github.com/lgou2w/HoYo.Gacha#readme"
repository = "https://github.com/lgou2w/HoYo.Gacha"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
shadow-rs = "0.29.0"
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
byteorder = "1.5.0"
exponential-backoff = "1.2.0"
form_urlencoded = "1.2.1"
futures = { version = "0.3.30", default-features = false, features = ["std", "async-await"] }
once_cell = "1.19.0"
paste = "1.0.15"
reqwest = { version = "0.12.5", features = ["json", "stream"] }
sea-orm = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio", "macros", "runtime-tokio-native-tls"], default-features = false }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
shadow-rs = "0.29.0"
sqlx-core = "0.7.4"
tauri = { version = "1.7.1", features = ["clipboard-all", "dialog-all", "path-all", "process-all", "shell-all", "devtools"] }
thiserror = "1.0.61"
time = { version = "0.3.36", features = ["formatting", "serde", "macros", "serde-human-readable", "local-offset"] }
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.2"

[target."cfg(windows)".dependencies.windows]
version = "0.39.0"
features = [
  "Win32_UI_WindowsAndMessaging"
]

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
