[package]
name = "hoyo_gacha"
version = "0.3.7"
edition = "2021"
authors = ["lgou2w"]
description = "An unofficial tool for managing and analyzing your miHoYo gacha records"
homepage = "https://github.com/lgou2w/HoYo.Gacha#readme"
repository = "https://github.com/lgou2w/HoYo.Gacha"
readme = "../README.md"
license = "MIT OR Apache-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
shadow-rs = "0.26.1"
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
byteorder = "1.5.0"
exponential-backoff = "1.2.0"
form_urlencoded = "1.2.1"
futures = { version = "0.3.30", default-features = false, features = ["std", "async-await"] }
once_cell = "1.19.0"
paste = "1.0.14"
reqwest = { version = "0.11.23", features = ["json", "stream"] }
sea-orm = { version = "0.12.12", features = ["sqlx-sqlite", "runtime-tokio", "macros", "runtime-tokio-native-tls"], default-features = false }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
shadow-rs = "0.26.1"
sqlx-core = "0.7.3"
tauri = { version = "1.5.4", features = ["clipboard-all", "dialog-all", "path-all", "process-all", "shell-all", "devtools"] }
thiserror = "1.0.56"
time = { version = "0.3.31", features = ["formatting", "serde", "macros", "serde-human-readable", "local-offset"] }
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
