[package]
name = "src-tauri"
version = "0.2.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
byteorder = "1.4.3"
chrono = { version = "0.4.23", default-features = false, features = ["std", "clock"] }
lazy_static = "1.4.0"
serde = { version = "1.0.152", features = ["derive"] }
tauri = { version = "1", features = ["api-all"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
