[package]
name = "genshin-gacha"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
chrono = { version = "0.4.22", features = ["std"] }
form_urlencoded = "1.1.0"
regex = { version = "1.6.0", features = ["std"] }
