name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            platform: windows-latest

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust environment
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm tauri build
        
      - name: Upload MSI build
        uses: actions/upload-artifact@v3
        with:
          name: HoYo.Gacha.MSI
          path: D:\a\HoYo.Gacha\HoYo.Gacha\target\release\bundle\msi\HoYo_Gacha_0.3.10_x64_zh-CN.msi

      - name: Upload NSIS build
        uses: actions/upload-artifact@v3
        with:
          name: HoYo.Gacha.NSIS
          path: D:\a\HoYo.Gacha\HoYo.Gacha\target\release\bundle\nsis\HoYo_Gacha_0.3.10_x64-setup.exe
