name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_name: Windows
            platform: windows-latest

    name: ${{ matrix.build_name }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install Node and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Get version information
        id: extract_version
        run: |
          echo "version=$(pnpm pkg get version | tr -d \")" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: ${{ github.event.repository.name }}-${{ steps.extract_version.outputs.version }}-${{ steps.extract_version.outputs.commit }}-${{ matrix.build_name }}
          path: |
            target/release/*.exe
            target/release/bundle/msi/*.msi
